### Testing the feng code with test precinct data

https://github.com/mhcfeng/precinct

In [11]:
import numpy as np


In [1]:
# lower_neighbors: This function takes a list of adjacencies and a vertex as input and returns a list of neighbors that have a lower index than the given vertex.
def lower_neighbors(adjacencies, vertex):
    return [v for v in adjacencies[vertex] if v < vertex]

In [3]:
def incremental_vr(V, adjacencies, maxDimension):
    Vnew = list(V)
    for vertex in np.arange(len(adjacencies)):
        N = sorted(lower_neighbors(adjacencies, vertex))
        add_cofaces(adjacencies, maxDimension, [vertex], N, Vnew)
    return Vnew

In [4]:
#add_cofaces: This function is a recursive helper function used by incremental_vr to add cofaces to the VR complex. 
# It checks if a face (a simplex) is not already in the list V, and if it is not, it appends it. 
# Then, it recursively adds cofaces by extending the face with neighbors from the lower neighbors.

def add_cofaces(adjacencies, maxDimension, face, N, V):
    if sorted(face) not in V:
        V.append(sorted(face))
    if len(face) >= maxDimension:
        return
    else:
        for vertex in N:
            coface = list(face)
            coface.append(vertex)
            M = list(set(N) & set(lower_neighbors(adjacencies, vertex)))
            add_cofaces(adjacencies, maxDimension, coface, M, V)

In [5]:
def replace_face(V):
    Vnew = []
    for face in V:
        if len(face) == 1:
            Vnew.append([len(Vnew)])
        else:
            Vnew_face = []
            for vertexIdx in np.arange(len(face)):
                subface = list(face)
                subface.pop(vertexIdx)
                subfaceIdx = V.index(subface)
                Vnew_face.append(subfaceIdx)
            Vnew.append(sorted(Vnew_face))
    return Vnew

#### Now let's create the test data

In [6]:
precinct_list = [
    [0, [1, 2, 3], "0.75"],
    [1, [0, 2], "0.5"],
    [2, [0, 1, 3], "0.9"],
    [3, [0, 2], "0.6"]
]

#### Computing the form_simplicial_complex method step by step

In [7]:
adjacencies = list(map(lambda m: m[1], precinct_list))

###### map(lambda m: m[1], precinct_list): This part applies the lambda function to each element (m) in precinct_list and extracts the second element (index 1) from each sublist. In this case, it's the list of neighboring precincts

In [8]:
adjacencies

[[1, 2, 3], [0, 2], [0, 1, 3], [0, 2]]

In [12]:
preferences = np.asarray(list(map(lambda m: float(m[2]), precinct_list)))

In [14]:
preferences

array([0.75, 0.5 , 0.9 , 0.6 ])

### Incremental algorithm

In [10]:
V = []

In [11]:
V = incremental_vr(V, adjacencies, 3)

In [12]:
V

[[0],
 [1],
 [0, 1],
 [2],
 [0, 2],
 [1, 2],
 [0, 1, 2],
 [3],
 [0, 3],
 [2, 3],
 [0, 2, 3]]

In [59]:
adjacencies

[[1, 2, 3], [0, 2], [0, 1, 3], [0, 2]]

In [69]:
vertex = 3
[v for v in adjacencies[vertex] if v < vertex]

[0, 2]

In [70]:
# def incremental_vr(V, adjacencies, maxDimension):
#     Vnew = list(V)
#     for vertex in np.arange(len(adjacencies)):
#         N = sorted(lower_neighbors(adjacencies, vertex))
#         add_cofaces(adjacencies, maxDimension, [vertex], N, Vnew)
#     return Vnew

In [71]:
Vnew = list(V)

for vertex in np.arange(len(adjacencies)):
        print(vertex)
        N = sorted(lower_neighbors(adjacencies, vertex))
        print(N)


0
[]
1
[0]
2
[0, 1]
3
[0, 2]


In [73]:
# def incremental_vr(V, adjacencies, maxDimension):
#     Vnew = list(V)
#     for vertex in np.arange(len(adjacencies)):
#         N = sorted(lower_neighbors(adjacencies, vertex))
#         add_cofaces(adjacencies, maxDimension, [vertex], N, Vnew)
#     return Vnew

In [72]:
# def add_cofaces(adjacencies, maxDimension, face, N, V):
#     if sorted(face) not in V:
#         V.append(sorted(face))
#     if len(face) >= maxDimension:
#         return
#     else:
#         for vertex in N:
#             coface = list(face)
#             coface.append(vertex)
#             M = list(set(N) & set(lower_neighbors(adjacencies, vertex)))
#             add_cofaces(adjacencies, maxDimension, coface, M, V)

In [87]:
#add_cofaces: This function is a recursive helper function used by incremental_vr to add cofaces to the VR complex. 
# It checks if a face (a simplex) is not already in the list V, and if it is not, it appends it. 
# Then, it recursively adds cofaces by extending the face with neighbors from the lower neighbors.


In [77]:
adjacencies

[[1, 2, 3], [0, 2], [0, 1, 3], [0, 2]]

In [90]:
maxDimension = 3

In [91]:
V = []

In [92]:
Vnew = list(V)

In [93]:
Vnew

[]

In [94]:
# ------------ above code only run one time -----------------

In [102]:
vertex = 1

In [103]:
N = sorted(lower_neighbors(adjacencies, vertex))

In [104]:
N

[0]

In [105]:
face = [vertex]

In [106]:
face

[1]

In [107]:
if sorted(face) not in V:
    V.append(sorted(face))

In [108]:
V

[[0], [1]]

In [111]:
if len(face) >= maxDimension:
    print("return")
else:
    for vertex in N:
        coface = list(face)
        coface.append(vertex)
        M = list(set(N) & set(lower_neighbors(adjacencies, vertex)))
        print(M)
        # add_cofaces(adjacencies, maxDimension, coface, M, V)

[]


In [110]:
np.arange(4)

array([0, 1, 2, 3])

In [15]:
preferences

array([0.75, 0.5 , 0.9 , 0.6 ])

In [17]:
np.floor((1 - np.abs(preferences)))

array([0., 0., 0., 0.])

In [14]:
entryTimes = np.floor((1 - np.abs(preferences)) * 100 / 5)

In [15]:
entryTimes

array([ 5., 10.,  1.,  8.])

In [16]:
entryTimesSub = [entryTimes[max(simplex) - 1] for simplex in V]

In [17]:
entryTimesSub

[8.0, 5.0, 5.0, 10.0, 10.0, 10.0, 10.0, 1.0, 1.0, 1.0, 1.0]

In [18]:
phatFormatV = replace_face(V)

In [19]:
phatFormatV

[[0],
 [1],
 [0, 1],
 [3],
 [0, 3],
 [1, 3],
 [2, 4, 5],
 [7],
 [0, 7],
 [3, 7],
 [4, 8, 9]]