Mortality Data Grouping # No data printed

In [2]:
# Import Libraries
import numpy as np
import pandas as pd
import geopandas as gpd

In [4]:
# Import all the mortality data for 2018
mort_2018 = pd.read_csv('/Users/h6x/ORNL/git/WORKSTAION GIT/universal-experiment-lab/experiment_10_multiple_variables_adj_package/data/mort_2018.csv')

/var/folders/j3/904q7dbj02j_jyjz7pvfgz384d40kw/T/ipykernel_46534/679614863.py:2: DtypeWarning: Columns (35) have mixed types. Specify dtype option on import or set low_memory=False.
  mort_2018 = pd.read_csv('/Users/h6x/ORNL/git/WORKSTAION GIT/universal-experiment-lab/experiment_10_multiple_variables_adj_package/data/mort_2018.csv')


In [16]:
# mort_2018.columns

Let's only consider Texas

In [6]:
texas_mortality = mort_2018[mort_2018['occurrence_state'] == 'TX']

In [7]:
# ICD codes for drug overdose deaths

# X40-X44: Accidental poisoning by and exposure to drugs
# X60-X64: Intentional self-poisoning by and exposure to drugs
# X85: Assault by drugs
# Y10-Y14: Poisoning by and exposure to drugs, undetermined

ICD_codes = ['X40', 'X41', 'X42', 'X43', 'X44', 'X60', 'X61', 'X62', 'X63', 'X64', 'X85', 'Y10', 'Y11', 'Y12', 'Y13', 'Y14']

In [9]:
# filter by ICD codes
texas_drug_mortality = texas_mortality[texas_mortality['cause of death_icd10'].str.contains('|'.join(ICD_codes))]

In [10]:
# make occurrence_county as an string and  if not 3 digits, add leading zero
texas_drug_mortality['occurrence_county'] = texas_drug_mortality['occurrence_county'].astype(str).str.zfill(3)

# add 48 to the county code in the occurrence_county column: 48 is the FIPS code for Texas
texas_drug_mortality['occurrence_county'] = '48' + texas_drug_mortality['occurrence_county']

/var/folders/j3/904q7dbj02j_jyjz7pvfgz384d40kw/T/ipykernel_46534/1455871586.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  texas_drug_mortality['occurrence_county'] = texas_drug_mortality['occurrence_county'].astype(str).str.zfill(3)
/var/folders/j3/904q7dbj02j_jyjz7pvfgz384d40kw/T/ipykernel_46534/1455871586.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  texas_drug_mortality['occurrence_county'] = '48' + texas_drug_mortality['occurrence_county']


Group by county and sum the number of deaths

In [11]:
# for each county count the number of deaths and store in a new df
texas_county_deaths = texas_drug_mortality.groupby('occurrence_county').size().reset_index(name='deaths')


Groupby county and sex and sum the number of deaths

In [12]:
texas_county_sex_deaths = texas_drug_mortality.groupby(['occurrence_county', 'sex']).size().reset_index(name='deaths')

In [13]:
texas_drug_mortality['age_recode_27'].unique()

array([16, 17,  8, 12, 13, 10, 20, 11, 18, 21, 14, 19, 15,  9, 22,  2, 23,
       24, 25,  1])

In [14]:
texas_drug_mortality['age_recode_52'].unique()

array([36, 37, 28, 32, 33, 30, 40, 31, 38, 41, 34, 39, 35, 29, 42, 12, 13,
       15, 43, 44, 45,  2])

In [15]:
texas_drug_mortality['detail_age'].unique()

array([1053, 1059, 1014, 1034, 1036, 1030, 1021, 1073, 1057, 1038, 1029,
       1033, 1060, 1032, 1024, 1028, 1075, 1043, 1054, 1066, 1055, 1047,
       1044, 1058, 1052, 1056, 1023, 1048, 1042, 1037, 1020, 1027, 1045,
       1041, 1035, 1019, 1046, 1067, 1061, 1022, 1084, 1069, 1040, 1026,
       1018, 1063, 1051, 1025, 1017, 1050, 1068, 1039, 1078, 1031, 1071,
       1070, 1064, 1049, 1081, 1015, 1062, 1083, 1016, 1065, 1077, 2001,
       1080, 1074, 1072, 1076, 1082, 2002, 2004, 1089, 1091, 1095, 1013,
       1088, 5001])